// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJQ2jN2OZsuoSRZMASg_Zw5RgmZ8X6Ei0',
    appId: '1:1068910061713:web:771458f0be129023553730',
    messagingSenderId: '1068910061713',
    projectId: 'ayums-11ds',
    authDomain: 'ayums-11ds.firebaseapp.com',
    storageBucket: 'ayums-11ds.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsfavXMV-Ek1IMzJVNdYaGqpecYuBv-xw',
    appId: '1:1068910061713:android:1addc39b3d69a66e553730',
    messagingSenderId: '1068910061713',
    projectId: 'ayums-11ds',
    storageBucket: 'ayums-11ds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjWBooPKOjpQrP5m5HLZqv7CsgJ0Nzpuc',
    appId: '1:1068910061713:ios:d4c9d380a828e70b553730',
    messagingSenderId: '1068910061713',
    projectId: 'ayums-11ds',
    storageBucket: 'ayums-11ds.appspot.com',
    iosBundleId: 'com.example.countdownApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjWBooPKOjpQrP5m5HLZqv7CsgJ0Nzpuc',
    appId: '1:1068910061713:ios:d4c9d380a828e70b553730',
    messagingSenderId: '1068910061713',
    projectId: 'ayums-11ds',
    storageBucket: 'ayums-11ds.appspot.com',
    iosBundleId: 'com.example.countdownApp',
  );
}
